CREATE TABLE IF NOT EXISTS {db}.canonical_swaps (
`block_num` UInt32,
`block_hash` String,
`timestamp` DateTime('UTC'),
`minute` UInt32 MATERIALIZED toRelativeMinuteNum(timestamp),
`transaction_index` UInt32,
`instruction_index` UInt32,
`signature` String,
`fee_payer` String,
`signers_raw` String,
`signers` Array(String) MATERIALIZED splitByChar(',', signers_raw),
`signer` String MATERIALIZED if(length(signers) > 0, signers[1], ''),
`fee` UInt64 DEFAULT 0,
`compute_units_consumed` UInt64 DEFAULT 0,
`program_id` LowCardinality(String),
`stack_height` UInt32,
`protocol` Enum8('unspecified' = 0, 'boop' = 1, 'darklake' = 2, 'dumpfun' = 3, 'jupiter_v4' = 4, 'jupiter_v6' = 5, 'meteora_daam' = 6, 'meteora_dlmm' = 7, 'orca_whirlpool' = 8, 'pumpfun' = 9, 'pumpfun_amm' = 10, 'raydium_amm_v4' = 11, 'raydium_clmm' = 12, 'raydium_cpmm' = 13, 'raydium_launchpad' = 14, 'meteora_amm' = 15, 'byreal' = 16, 'moonshot' = 17, 'pancakeswap' = 18, 'spl_token_swap' = 19, 'okx_dex' = 20),
`amm` String,
`amm_pool` String,
`user` String,
`input_mint` String,
`input_amount` UInt64,
`output_mint` String,
`output_amount` UInt64,
`event_id` String,
`source_instruction_index` UInt32,
`transfer_verified` UInt8,
`verification_failure` LowCardinality(String)
) ENGINE=ReplacingMergeTree PARTITION BY toDate(timestamp) ORDER BY (block_hash,transaction_index,instruction_index);
